### ISSUE TITLE
Make this available in maven central

### ISSUE THREAD

**Issue by francisdb** [fcabestre/Scala-MQTT-client#2]
If you want people to use this (and I want to), this is the first step.

Start with getting an account for the sonatype oss nexus and follow this guide:
http://www.cakesolutions.net/teamblogs/publishing-artefacts-to-oss-sonatype-nexus-using-sbt-and-travis-ci

**Comment by fcabestre** [comment]
I was planning to push released artifacts to [Bintray](https://bintray.com/fcabestre/releases/scala-mqtt-client/view) and I had all prepared for that. Stay tuned...

**Comment by francisdb** [comment]
I guess that would also do as a start, would however still try to get it into maven central as that avoids having to add an extra repo (which is bad practice for reproducible builds later on)

**Comment by francisdb** [comment]
Anyway it's afterwards just a matter of changing publishing url I suppose

**Comment by fcabestre** [comment]
I agree that adding additional resolvers is cumbersome when maven central works out of the box. I've found that Bintray can be used as a [gateway to maven central](http://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/). Anyway, I initially chose Bintray for no particular reason except testing something new and because I used to use Artifactory which is a JFrog product as well. Moreover creating a maven central repository is not as easy as a Bintray account. 

However, I'm seriously considering this option now. But I will not implement it before a couple of weeks : time to get the maven central repository, enjoy a week of ski holidays :smile: and then put all the things together.

**Comment by fcabestre** [comment]
I've just added an [issue](https://issues.sonatype.org/browse/OSSRH-13688) to the Sonatype's Jira to request a repository hosting.

**Comment by francisdb** [comment]
ok cool, enjoy your holidays

**Comment by fcabestre** [comment]
I have completed the set up of my Sonatype OSSRH with Maven Central syncing. Currently there is a version ```scala-mqtt-client-0.5.0``` version available from Maven Central. Enjoy... If it is of any use.

P.S.: And I had very good holidays indeed :smile:

**Comment by cridmann** [comment]
Great!  Thanks for all the hard work with this so far - will be interesting to see some of your future ideas.

Cheers

**Comment by francisdb** [comment]
Great :+1:

**Comment by francisdb** [comment]
No issues so far. Using the client to listen to # with ExactlyOnce. Is this ExactlyOnce correctly implemented?
Are you using gitter, could not find a room for this repo?

**Comment by fcabestre** [comment]
I didn't do anything to enable gitter. So I suppose it's currently disabled. As far as I understand there is not much effort to do to implement ```ExactlyOnce``` from a subscriber's standpoint. So I'd say it's correctly implemented to listen to ```#```.
